







day1
' 金澤城
' 金澤美食蟹
' 兼六園
' 金澤近江町市場

day2
JR D1
' 長野善光寺 有點遠
' 長野善光寺廟前街
' ' 地獄谷野猿公苑
' 歴史の宿金具屋

day3
JR D2
' 雪場玩雪 長野滑雪場
' 白馬JR 1天


day4
JR D3
' [軽井沢]
' 冬季的淺間山
' 1h30min $9900
' 輕井澤王子購物廣場 near station

day5
JR D4
冨山？
金沢？
イベート？
冬花火？
其他地區 沒有PASS也ok


day6
JR D5
or ohters?
to 京都


JR D6


JR D7

' 12天玩
' 六天北部
' 2天中部
' 四天西部

' 群馬?